Docker:
  User: puck
  Main: web
  Images:
    php: ~
    search:
      ports:
        - 9200
      volumes:
        - search
    mysql:
      ports:
        - 3306
      volumes:
        - mysql
    memcached:
      ports:
        - 11211
    mongo:
      ports:
        - 27017
      volumes:
        - mongo
    web:
      hostname: local.znanylekarz.pl
      useTTY: true
      require:
        - php
        - mysql
        - mongo
        - memcached
        - search
      ports:
        - 80
        - 22
      volumes:
        - docplanner
        - platform
